Repository Peripli/service-broker-proxy, pull requests merged in 2019-06, with the labels that each got.

#77 adopt sm fixits
  Gopkg.lock
  Gopkg.toml
  pkg/filter/basic_auth.go
  pkg/filter/basic_auth_test.go
  pkg/osb/broker_fetcher.go
  pkg/osb/broker_fetcher_test.go
  pkg/osb/osb_suite_test.go
  pkg/sbproxy/reconcile/reconciler_test.go
  pkg/sbproxy/sbproxy.go
Labels: request review

#79 Do not panic in hidden layer
  Gopkg.lock
  pkg/sbproxy/sbproxy.go
  pkg/sbproxy/sbproxy_test.go
Labels: request review

#81 Fix Broker Name
  pkg/sbproxy/reconcile/reconcile_visibilities.go
Labels: bug, request review

#78 Adapt to SM not sending last_known_revision when no notifications are present
  pkg/sbproxy/notifications/producer.go
  pkg/sbproxy/notifications/producer_test.go
Labels: breaking-change, request review

#82 Fix unlimited go routines
  pkg/platform/broker_client.go
  pkg/platform/platformfakes/fake_broker_client.go
  pkg/sbproxy/reconcile/reconcile_brokers.go
  pkg/sbproxy/reconcile/reconcile_brokers_test.go
  pkg/sbproxy/reconcile/reconcile_settings.go
  pkg/sbproxy/reconcile/reconcile_settings_test.go
  pkg/sbproxy/reconcile/reconcile_visibilities.go
  pkg/sbproxy/reconcile/reconcile_visibilities_test.go
  pkg/sbproxy/reconcile/resyncer.go
  pkg/sbproxy/sbproxy_test.go
  pkg/sm/client.go
  pkg/sm/client_test.go
  pkg/sm/smfakes/fake_client.go
  pkg/sm/types.go
Labels: request review

#83 Register proxy broker URLs to point to SM instead of Proxy
  Gopkg.lock
  pkg/sbproxy/notifications/handlers/broker_handler.go
  pkg/sbproxy/notifications/handlers/broker_handler_test.go
  pkg/sbproxy/reconcile/reconcile_brokers.go
  pkg/sbproxy/reconcile/reconcile_brokers_test.go
  pkg/sbproxy/reconcile/reconcile_settings.go
  pkg/sbproxy/reconcile/reconcile_settings_test.go
  pkg/sbproxy/reconcile/reconcile_suite_test.go
  pkg/sbproxy/reconcile/reconcile_visibilities_test.go
  pkg/sbproxy/reconcile/resyncer.go
  pkg/sbproxy/sbproxy.go
  pkg/sbproxy/sbproxy_test.go
Labels: release, request review
