Repository Peripli/service-broker-proxy, pull requests merged in 2019-05, with the labels that each got.

#63 adjust notification applying
  Gopkg.lock
  Gopkg.toml
  pkg/sbproxy/notifications/consumer.go
  pkg/sbproxy/notifications/handlers/broker_handler.go
  pkg/sbproxy/notifications/handlers/broker_handler_test.go
  pkg/sbproxy/notifications/handlers/visibilities_handler.go
  pkg/sbproxy/notifications/handlers/visibility_handler_test.go
  pkg/sbproxy/reconcile/reconcile_task.go
Labels: request review

#65 [SVCMGR-510] Adjust broker names when they are overtaken from SM
  pkg/sbproxy/reconcile/reconcile_brokers.go
  pkg/sbproxy/reconcile/reconcile_brokers_test.go
  pkg/sbproxy/reconcile/reconcile_visibilities.go
  pkg/sbproxy/reconcile/reconcile_visibilities_test.go
Labels: request review

#62 Integrate reconciler and notification producer
  Gopkg.lock
  pkg/sbproxy/reconcile/reconcile_brokers.go
  pkg/sbproxy/reconcile/reconcile_brokers_test.go
  pkg/sbproxy/reconcile/reconcile_task.go
  pkg/sbproxy/reconcile/reconcile_task_test.go
  pkg/sbproxy/reconcile/reconcile_visibilities.go
  pkg/sbproxy/reconcile/reconcile_visibilities_test.go
  pkg/sbproxy/reconcile/reconciler.go
  pkg/sbproxy/reconcile/reconciler_test.go
  pkg/sbproxy/reconcile/resyncer.go
  pkg/sbproxy/sbproxy.go
Labels: request review

#66 Use broker name instead of id
  Gopkg.lock
  pkg/sbproxy/notifications/handlers/broker_handler.go
  pkg/sbproxy/notifications/handlers/broker_handler_test.go
  pkg/sbproxy/notifications/handlers/visibilities_handler.go
  pkg/sbproxy/notifications/handlers/visibility_handler_test.go
Labels: request review

#64 [WIP] Notifications
  Gopkg.lock
  Gopkg.toml
  pkg/platform/broker_client.go
  pkg/platform/platformfakes/fake_broker_client.go
  pkg/platform/platformfakes/fake_catalog_fetcher.go
  pkg/platform/platformfakes/fake_client.go
  pkg/platform/platformfakes/fake_visibility_client.go
  pkg/platform/types.go
  pkg/platform/visibility_client.go
  pkg/sbproxy/notifications/consumer.go
  pkg/sbproxy/notifications/handlers/broker_handler.go
  pkg/sbproxy/notifications/handlers/broker_handler_test.go
  pkg/sbproxy/notifications/handlers/handlers_suite_test.go
  pkg/sbproxy/notifications/handlers/helpers.go
  pkg/sbproxy/notifications/handlers/helpers_test.go
  pkg/sbproxy/notifications/handlers/visibilities_handler.go
  pkg/sbproxy/notifications/handlers/visibility_handler_test.go
  pkg/sbproxy/notifications/producer.go
  pkg/sbproxy/notifications/producer_test.go
  pkg/sbproxy/options.go
  pkg/sbproxy/options_test.go
  pkg/sbproxy/reconcile/reconcile_brokers.go
  pkg/sbproxy/reconcile/reconcile_brokers_test.go
  pkg/sbproxy/reconcile/reconcile_settings.go
  pkg/sbproxy/reconcile/reconcile_task.go
  pkg/sbproxy/reconcile/reconcile_task_test.go
  pkg/sbproxy/reconcile/reconcile_visibilities.go
  pkg/sbproxy/reconcile/reconcile_visibilities_test.go
  pkg/sbproxy/reconcile/reconciler.go
  pkg/sbproxy/reconcile/reconciler_test.go
  pkg/sbproxy/reconcile/resyncer.go
  pkg/sbproxy/sbproxy.go
  pkg/sm/client_test.go
  pkg/sm/options.go
  pkg/sm/options_test.go
  pkg/sm/types.go
Labels: wip

#73 Reorder resync
  pkg/sbproxy/reconcile/reconcile_brokers.go
  pkg/sbproxy/reconcile/reconcile_brokers_test.go
  pkg/sbproxy/reconcile/reconcile_settings_test.go
  pkg/sbproxy/reconcile/reconcile_suite_test.go
  pkg/sbproxy/reconcile/reconcile_visibilities.go
  pkg/sbproxy/reconcile/reconcile_visibilities_test.go
  pkg/sbproxy/reconcile/reconciler.go
  pkg/sbproxy/reconcile/resyncer.go
Labels: request review

#74 Remove platform visibility cache
  Gopkg.lock
  Gopkg.toml
  pkg/sbproxy/reconcile/reconcile_brokers.go
  pkg/sbproxy/reconcile/reconcile_brokers_test.go
  pkg/sbproxy/reconcile/reconcile_settings.go
  pkg/sbproxy/reconcile/reconcile_settings_test.go
  pkg/sbproxy/reconcile/reconcile_visibilities.go
  pkg/sbproxy/reconcile/reconcile_visibilities_test.go
  pkg/sbproxy/reconcile/resyncer.go
  pkg/sbproxy/sbproxy.go
Labels: request review

#75 Issues with broker naming scheme in platforms
  pkg/sbproxy/notifications/handlers/broker_handler.go
  pkg/sbproxy/notifications/handlers/broker_handler_test.go
  pkg/sbproxy/notifications/handlers/handlers_suite_test.go
  pkg/sbproxy/notifications/handlers/visibilities_handler.go
  pkg/sbproxy/notifications/handlers/visibility_handler_test.go
  pkg/sbproxy/reconcile/reconcile_brokers.go
  pkg/sbproxy/reconcile/reconcile_brokers_test.go
  pkg/sbproxy/reconcile/reconcile_suite_test.go
  pkg/sbproxy/reconcile/reconcile_visibilities.go
  pkg/sbproxy/reconcile/reconcile_visibilities_test.go
Labels: bug, request review
